
global:
  namespaceOverride: rust-session-store
  postgresql:
    postgresqlPassword: postgres

#
#mongodb:
#  publicPath: "/mongodb"
#  auth:
#    rootPassword: "root"
#  externalAccess:
#    enabled: true

postgresql:

  postgresqlUsername: postgres
  postgresqlPostgresPassword: postgres
  networkPolicy:
    explicitNamespacesSelector:
      name: rust-session-store
  publicPort: 30004

redis:
  usePassword: false
  publicPort: 30005