apiVersion: v1
kind: Service
metadata:
  name: postgres-external-access
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: postgresql
  type: NodePort
  ports:
    -
      port: 5432
      protocol: TCP
      nodePort: {{ .Values.postgresql.publicPort }}