apiVersion: v1
kind: Service
metadata:
  name: redis-external-access
  namespace: default
spec:
  selector:
    app: redis
    role: master
  type: NodePort
  ports:
    -
      port: 6379
      protocol: TCP
      nodePort: {{ .Values.redis.publicPort }}